### ISSUE TITLE
Missing AMI for region ap-east-1

### ISSUE THREAD

**Issue by adisbladis** [NixOS/nixos-org-configurations#105]
The region is in the AMI upload script but not in the AMI list https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/ec2-amis.nix.

cc @AmineChikhaoui

**Comment by adisbladis** [comment]
I also noticed `eu-north-1` was missing from the script. I've added it on nixpkgs `master` and `release-19.09`.

**Comment by AmineChikhaoui** [comment]
For some reason an Auth failure happens with this region when running the script:
```
Copying ami-071082f0fa035374f to ap-east-1

An error occurred (AuthFailure) when calling the CopyImage operation: AWS was not able to validate the provided access credentials
Waiting for image  to be available

An error occurred (AuthFailure) when calling the DescribeImages operation: AWS was not able to validate the provided access credentials
 ... state=
Unexpected AMI state: ''
```
Will look into why that's happening.

**Comment by AmineChikhaoui** [comment]
Ah looks like it needs to be manually enabled in the AWS account
