### ISSUE TITLE
update AWS AMIs and Virtual Box Images to 20.03

### ISSUE THREAD

**Issue by knl** [NixOS/nixos-org-configurations#109]
Now that 20.03 is out (congrats!), it would be great to have official AMIs out there as well, otherwise this page looks broken:

https://nixos.org/download.html (tab Amazon EC2).

[In this discussion on Discourse](https://discourse.nixos.org/t/what-is-the-process-for-publishing-the-official-nixos-amis/4581/2?u=knl) @grahamc mentions that maybe release documentation needs updating to include building AMIs as the part of the release.

cc @AmineChikhaoui @worldofpeace

**Comment by garbas** [comment]
Is anybody working on this? Currently the Amazon EC2 tab looks empty.

**Comment by AmineChikhaoui** [comment]
@garbas @knl I added EC2 amis few days ago in https://github.com/NixOS/nixpkgs/pull/86060, not sure how it ends up in the homepage maybe once the channel propagates ?

**Comment by AmineChikhaoui** [comment]
oh the channel is already past that commit so that's likely not related

**Comment by garbas** [comment]
@AmineChikhaoui oh i see, thank you for quick answer. I'll take it from here (the nixos-homepage part) and see why it is not showing up.

**Comment by garbas** [comment]
this is now done. thank you all.
