### ISSUE TITLE
Install a multi-user IRC bouncer

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixos-org-configurations#11]
To make it as easy as possible for users to connect to the community, it would be great if nixos.org would serve a web interface with history for the IRC channel where people can use IRC without a client.

A good candidate seem to be https://github.com/ircanywhere/ircanywhere .

**Comment by domenkozar** [comment]
What's wrong with https://webchat.freenode.net/?

**Comment by grahamc** [comment]
I'd suggest we close this.
