### ISSUE TITLE
Prepare public images in the NixOS GCP account

### ISSUE THREAD

**Issue by tewfik-ghariani** [NixOS/nixos-org-configurations#110]
As introduced per https://github.com/nix-community/nixops-gce/pull/1 , we can switch from creating our own bootstrap-image per deployment to having a public image in nixos GCP account available for us, similarly to amis in EC2

We then need to update the https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/gce-images.nix file while specifying the ***image family*** and the ***project name***

Here are the steps 

_Building an image from source_

```
$ gcloud compute images create nixos-18091228a4c4cbb613c-x86-64-linux  \
              --source-uri gs://nixos-cloud-images/nixos-image-18.09.1228.a4c4cbb613c-x86_64-linux.raw.tar.gz \
              --family=nixos-1809
```
_Making the image public_

```
$ gcloud compute images  add-iam-policy-binding nixos-18091228a4c4cbb613c-x86-64-linux \
             --member='allAuthenticatedUsers'                                                                              \
             --role='roles/compute.imageUser' 
```

And then that image may be used publicly so that all nixops users won't have the need to provision their own 'bootstrap-image' resource for every deployment. 

 ```
$ gcloud compute instances create test-nixos-18  \
             --image-family=nixos-1809                        \
             --zone=europe-west1-c                             \
             --image-project=predictix-operations
```

cc @AmineChikhaoui

**Comment by garbas** [comment]
What if we setup a GitHub actions workflow to do this ([example](https://github.com/GoogleCloudPlatform/github-actions/blob/master/example-workflows/gce/.github/workflows/gce.yaml]) only when nixpkgs-channels gets updated?

This would allow us to have this images always up to date. And I assume we could do the same for EC2 and Azume images.

What we would have to change is the location of **channels -> latest images** mapping ([gce-images.nix](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/gce-images.nix), [ec2-amis.nix](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/ec2-amis.nix), [azure-images](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/azure-images.nix), ...). It never made sense to me that we are keeping this information in nixpkgs anyway. I think having this mappings as part of the artifacts of each evaluation would make much more sense.

**Comment by AmineChikhaoui** [comment]
@tewfik-ghariani building the image involves a `nix-build` as well which maybe we can do in hydra like we do for AWS now.

@garbas I think Github actions run in containers ? so a VM build will likely not work I think but if this is prebuilt in hydra like for amazon images then it would be just pull the latest build and create an image out of it. Maybe also we can test the image as part of the Github action by spinning up a vm, making sure it boots correctly then tearing it down.

**Comment by AmineChikhaoui** [comment]
Oh wait I just saw the example link @garbas , looks like they do a `docker build` in the action so that probably doesn't run inside a container.

**Comment by garbas** [comment]
@AmineChikhaoui currently we have in nixpkgs a few attribute sets which map from "nixos version" to "uploaded image" ([gce-images.nix](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/gce-images.nix), [ec2-amis.nix](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/ec2-amis.nix), [azure-images.nix](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/azure-images.nix), ...). We would have to update this each time we upload new images. I think it would be nicer to have this somewhere else. Having them right next to the [evaluation artifacts](http://releases.nixos.org/?prefix=nixos/20.03/nixos-20.03.1739.4d373182597/) would be where I would put them (eg. in some json file or something like that).

**Comment by garbas** [comment]
<dreaming>
We could also generate and upload all of other images for other cloud (or non-cloud) services. Taking the work that [nixos-generators](http://releases.nixos.org/?prefix=nixos/20.03/nixos-20.03.1739.4d373182597/) did and show it on the nixos website.
</dreaming>

**Comment by tewfik-ghariani** [comment]
Hello, can you please share the exact process to build/spin up GCE Images using the latest nixpkgs version as well as the encountered issues?

Will there be a need to make some changes to the create-gce.sh script in nixpkgs?

**Comment by tewfik-ghariani** [comment]
Done as part of https://github.com/nix-community/nixops-gce/pull/17 & https://github.com/NixOS/nixpkgs/pull/117021

Thanks @AmineChikhaoui!

Closing,
