### ISSUE TITLE
status.nixos.org: 19.09 should be marked as EOL

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixos-org-configurations#117]
I think that's achieved by flipping `metric.current` in prometheus: https://github.com/NixOS/nixos-org-configurations/blob/3294705/delft/eris/status-page/status.js#L120

**Comment by cole-h** [comment]
19.09 now appears as EOL on https://status.nixos.org/.

**Comment by vcunat** [comment]
It would be nice to know why it happened now and not [a month ago](https://github.com/NixOS/nixos-org-configurations/pull/120#issuecomment-689335070), and perhaps even document the workflow in a comment in the file.

**Comment by cole-h** [comment]
Agreed -- it would be nice to know, especially so that it could be added to the release manager wiki.
