### ISSUE TITLE
t2a.cunat.cz unreachable

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixos-org-configurations#118]
From the hydra.nixos.org logs:

```
Jul 28 13:09:44 ceres hydra-queue-runner[9427]: possibly transient failure building ‘/nix/store/4k1353pypg9jzq0nsmchq7w3rl0s2bg9-nixpkgs-metrics.drv’ on ‘root@t2a.cunat.cz’: error: --- Error --- hydra-queue-runner
Jul 28 13:09:44 ceres hydra-queue-runner[9427]: cannot connect to ‘root@t2a.cunat.cz’: ssh: connect to host t2a.cunat.cz port 22: No route to host
```

@vcunat Do you know what's up with this machine?

**Comment by vcunat** [comment]
Yes, I know... I'm sorry.  The machine is perfectly OK, but my ISP is giving me long-term problems, so I have no IPv6 and thus no nice way of Hydra reaching it from outside.

**Comment by edolstra** [comment]
Ah thanks. Do you think it's better to disable it in nix.machines for now?

**Comment by vcunat** [comment]
I have no idea what's the impact on the farm.  On my side it's free, as the IPv6 packets won't reach me.

**Comment by vcunat** [comment]
I connected `t2a` today, in a makeshift way at least.

**Comment by vcunat** [comment]
I finally managed to reestablish the connection (a week ago), and I trust it will hold now.  `t4b` seems to have been running fine for the whole week; now I also reverted `t2a` back from the makeshift solution.

You can remove `t4a`.  The board seems dead or something; I don't think I'll be able to revive it.  Maybe I'll consider adding some bigger machine instead (Zen* with 16+ threads?), in future...

**Comment by edolstra** [comment]
Thanks, t2a is building again!

**Comment by vcunat** [comment]
I believe you can re-enable `t2a` again.  (I'm not sure who disabled them this time.  There's no `t4b` yet but I expect to revive it eventually, no ETA though.)
