### ISSUE TITLE
Please increase `launchctl limit maxfiles` for Darwin builders

### ISSUE THREAD

**Issue by eqyiel** [NixOS/nixos-org-configurations#119]
I noticed this because Anki fails to build in the [`nixpkgs-20.03-darwin` jobset](https://hydra.nixos.org/build/125654233) with [`OSError: [Errno 24] Too many open files`](https://hydra.nixos.org/build/125654233/nixlog/1/tail).

The same derivation can build locally with a higher limit.  There's a sample LaunchDaemon to configure this here: https://eradman.com/entrproject/limits.html

I'm not sure what the consequences of this for virtualization are (like, does the guest use the host's file limit).

cc @grahamc because you wrote the README for the MacOS infrastructure 🙏

**Comment by grahamc** [comment]
I think this is done already, but if not please open a new issue :).
