### ISSUE TITLE
broken big-parallel feature on some Hydra machines

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixos-org-configurations#128]
Apparently for some machines the scheduler thinks they have the "big-parallel" feature but the builder itself disagrees.  We're then getting abortions like
```
Aborted: [31;1merror:[0m[34;1m --- Error --- nix-store[0m a '[33;1maarch64-linux[0m' with features {[33;1mbig-parallel[0m} is required to build '[33;1m/nix/store/kjvs406gd1gxa90fz614krnasv3p8wym-llvm-9.0.1.drv[0m', but I am a '[33;1maarch64-linux[0m' with features {[33;1mkvm, nixos-test, recursive-nix[0m}
```

[A current case](https://hydra.nixos.org/build/129195629) was aarch64 but _maybe_ I saw x86_64 kernel a couple days ago.

**Comment by vcunat** [comment]
This is starting to block channels due to kernel updates.  /cc @NixOS/infra

**Comment by grahamc** [comment]
nixUnstable seems to have broken the receipt of .drv files, and I can't roll out the change to the aarch64 builders fixing this problem (like I did to the x86 machines a few days ago) because of that. See #nixos-dev over the last 30 minutes or so.

**Comment by grahamc** [comment]
I opened a ticket about it: https://github.com/NixOS/nix/issues/4210

I doubt I'll be able to look much further in to this today.

**Comment by vcunat** [comment]
_Looks_ like it works now.
