### ISSUE TITLE
hydra.nixos.org seems to be down. 

### ISSUE THREAD

**Issue by wnklmnn** [NixOS/nixos-org-configurations#139]
Hi, 
I wanted to download an image for my rpi3 from hydra and noticed that hydra seems to be having some issues. 
Acording to the grafana board all services are failing.

https://status.nixos.org/grafana/d/fBW4tL1Wz/scheduled-task-state-channels-website?orgId=1&from=now-12h&to=now&refresh=10s

**Comment by grahamc** [comment]
It seems just the web interface, and not the evaluator or queue runner. Still, not great :D. It looks like someone is searching for packages in a hard loop, which is causing the down issue. Here is a PR which limits their query: https://github.com/NixOS/hydra/pull/853

**Comment by grahamc** [comment]
a follow up PR merged and deployed https://github.com/NixOS/hydra/pull/854 I think we can call this issue resolved
