### ISSUE TITLE
monitoring.nixos.org SSL certificate expired

### ISSUE THREAD

**Issue by jshholland** [NixOS/nixos-org-configurations#143]
Despite [`services.nginx.virtualHosts."monitoring.nixos.org".enableACME`](https://github.com/NixOS/nixos-org-configurations/blob/master/delft/eris.nix#L44) being set, the certificate expired yesterday (2021-03-18). This has a knock-on effect with status.nixos.org no longer working (see also NixOS/nixos-status#9).

**Comment by cole-h** [comment]
Seems fixed for me.

**Comment by jshholland** [comment]
Looks like @grahamc fixed it earlier today: https://logs.nix.samueldr.com/nixos/2021-03-19#4752940;
