### ISSUE TITLE
Remove wendy from the machine list

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixos-org-configurations#146]
We have a bunch of packages that are failing to build due to missing SSE 4.2 instruction set on wendy.

There's an issue https://github.com/NixOS/nixpkgs/issues/115425 that's waiting on Nix release, but that's going to take a while to be usable.

Since wendy is supposed to be retired anyway later this year and given that it won't play a huge role in terms of Linux workload, I'd suggest retiring it.

The alternative is to make it only run big-parallel and tests features.

Note that this is currently a big blocker for data science packages and it provides frustration as packages break all the time.

I'm happy to do the work myself if I can help in any way.

**Comment by grahamc** [comment]
Does nix consider the "mandatory features" field to be AND or OR? ie: can we say it must either be big parallel or kvm?

**Comment by domenkozar** [comment]
AFAIK it considers it an OR.

**Comment by grahamc** [comment]
Can you double check? If it is an AND, can you look at https://monitoring.nixos.org/grafana/d/MJw9PcAiz/hydra-jobs?viewPanel=2&orgId=1&refresh=30s and find the feature (kvm or big-parallel) type that has most demand?

**Comment by domenkozar** [comment]
> Can you double check?

From https://nixos.org/manual/nix/stable/#chap-distributed-builds

"A machine will only be used to build a derivation if all of the machine’s mandatory features appear in the derivation’s requiredSystemFeatures attribute."

>  If it is an AND, can you look at https://monitoring.nixos.org/grafana/d/MJw9PcAiz/hydra-jobs?viewPanel=2&orgId=1&refresh=30s and find the feature (kvm or big-parallel) type that has most demand?

big-parallel has "a lot" more demand from 1-year history.

**Comment by grahamc** [comment]
```
root@wendy.ewi.tudelft.nl i686-linux,x86_64-linux /var/lib/hydra/queue-runner/.ssh/id_buildfarm_rsa 16 3 kvm,big-parallel big-parallel
```

is its new config

**Comment by grahamc** [comment]
I'm going to close this now, wendy should only be building big-parallel jobs now. I think this mean that NixOS tests won't run there, though, will they? Are they big-parallel? (should they be?)

**Comment by domenkozar** [comment]
Thanks! Nope, NixOS tests won't run and I don't think they should be big-parallel as that flag implies lots of cores (most tests use 1-2 cores).

**Comment by domenkozar** [comment]
Seems like it was added back: https://github.com/NixOS/nixpkgs/issues/115425

**Comment by vcunat** [comment]
I believe it only runs `big-parallel` jobs, just as you suggested in the OP.  (Though wendy might be more trouble than worth anyway.)

**Comment by vcunat** [comment]
So the pytorch case could well be also blamed at https://github.com/NixOS/nixpkgs/commit/0d4abe5d4b6

**Comment by domenkozar** [comment]
Thanks for pointing that out :)

**Comment by vcunat** [comment]
Well, the same problem also happens with the `ike` machine: https://hydra.nixos.org/build/150103835

**Comment by mweinelt** [comment]
> This compiles in usually about 2h15m with a 2-core build, but about 10m
on a big-parallel machine.

Setting `big-parallel` on pytorch was a good idea. Wendy and Ike need to go. Why is this issue closed again without a proper fix?

**Comment by mweinelt** [comment]
Poking @NixOS/infra for feedback.

**Comment by mweinelt** [comment]
This continues to happen on a daily basis. Another hour of build time down the drain. https://hydra.nixos.org/build/151477633

**Comment by domenkozar** [comment]
Maybe @zimbatm could help us remove those two machines?

**Comment by grahamc** [comment]
I took out wendy  and ike and left a comment about why.
