### ISSUE TITLE
Support CORS for cache.nixos.org

### ISSUE THREAD

**Issue by fzakaria** [NixOS/nixos-org-configurations#156]
I have recently contributed an OpenAPI specification for Nix's binary cache.
You can view it at https://fzakaria.github.io/nix-http-binary-cache-api-spec (https://github.com/fzakaria/nix-http-binary-cache-api-spec).

I would like to be able to support users to send requests from the browser UI to play with the API unfortunately cache.nixos.org does not support CORS.

It returns the current failure:
```
Access to fetch at 'https://cache.nixos.org/nix-cache-info' from origin 'https://fzakaria.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
index.js:112 GET https://cache.nixos.org/nix-cache-info net::ERR_FAILED
```

Could Nix's S3 bucket be configured for CORS ?
https://docs.aws.amazon.com/AmazonS3/latest/userguide/cors.html

Please excuse me for opening the ticket here.
I wish GitHub allowed organizational level tickets that don't necessarily match a repository.

**Comment by edolstra** [comment]
Moved it to `nixos-org-configurations` since that's where we have our bucket policy.

**Comment by edolstra** [comment]
We do have a [CORS config](https://github.com/NixOS/nixos-org-configurations/blob/c33081dcb51bfd7db5a611b5a92ada805a6714c2/terraform/cache.tf#L14-L19):

```
# curl -H 'Origin: https://foo.example' -v https://nix-cache.s3.amazonaws.com/nix-cache-info
...
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET
< Access-Control-Max-Age: 3000
```

However, it looks like the CDN (cache.nixos.org) doesn't propagate these headers.

**Comment by fzakaria** [comment]
Thanks for moving to the correct repository; I'll be sure to remember it going forward.
I can update the example to not use the CDN in the meantime.

**Comment by fzakaria** [comment]
@edolstra looks like the **/nix-cache-info** path also returns **application/octet-stream** where the other paths return a content type of **text/xxxx** (i.e. text/x-nix-narinfo)

Maybe that should be fixed also.

**Comment by edolstra** [comment]
Please don't use nix-cache.s3.amazonaws.com directly, it's more expensive and slower than the CDN. Ideally it shouldn't allow access from clients other than the CDN...

**Comment by fzakaria** [comment]
Roger.
I wasn't using it for any serious workload; just testing my routes on https://fzakaria.github.io/nix-http-binary-cache-api-spec/

**Comment by fzakaria** [comment]
Yes I know that the /nar path is from NarInfo... I need to figure out how to use OpenAPI links https://swagger.io/docs/specification/links/ so that it works correctly

**Comment by zimbatm** [comment]
```
$ curl -I https://cache.nixos.org/nix-cache-info
HTTP/2 200 
x-amz-id-2: B55FUpLIfgr+d2r+aONecAf/BYgFO4Je5k4Rv1wW86dkxx64VQ4S/hA1yIZFl4rVx/JZc7ltPtUbC+OX6JB2Cw==
x-amz-request-id: 6T77BABC1J5C8TC8
last-modified: Fri, 24 May 2013 20:33:25 GMT
etag: "69d68de32bd6e6f0751e4cd5ae13e053"
content-type: application/octet-stream
server: AmazonS3
via: 1.1 varnish, 1.1 varnish
accept-ranges: bytes
date: Fri, 03 Sep 2021 07:35:15 GMT
age: 89456
x-served-by: cache-bwi5125-BWI, cache-cdg20737-CDG
x-cache: HIT, HIT
x-cache-hits: 1, 1
x-timer: S1630654515.351722,VS0,VE0
content-length: 51
```
