### ISSUE TITLE
nix-cache-info returns application/octet-stream

### ISSUE THREAD

**Issue by zimbatm** [NixOS/nixos-org-configurations#162]
@edolstra looks like the **/nix-cache-info** path also returns **application/octet-stream** where the other paths return a content type of **text/xxxx** (i.e. text/x-nix-narinfo)

Maybe that should be fixed also.

_Originally posted by @fzakaria in https://github.com/NixOS/nixos-org-configurations/issues/156#issuecomment-899634534_

**Comment by zimbatm** [comment]
That's now easy to change as I mapped the file in terraform. @edolstra should I set it to `text/plain`?

**Comment by fzakaria** [comment]
I think so -- it really is a Key-Value encoding but I don't know of any such `text/` MIME type for that.
I find it interesting that the JSON stuff is done post-processed in the Nix CLI.

Thanks for filing this @zimbatm

**Comment by edolstra** [comment]
I don't think `text/plain` is the correct MIME type, since this file is not intended for human consumption. In the absence of a dedicated MIME type for `nix-cache-info`, `application/octet-stream` is probably the best choice.

**Comment by fzakaria** [comment]
Can we keep it `text/X` at least ? Similar to `text/x-nix-narinfo` can it be `text/x-nix-cache-info` ?
It would make sense to keep the consistency here.

Is there an RFC to change the return type to JSON?
It's unfortunate it's directly served from S3 (although it makes the infrastructure much simpler!) since it can't return multiple formats based on the `Accept` header.

**Comment by zimbatm** [comment]
It would be helpful to outline the underlying motivation. The only one I can see is that it makes it easier to find out the cache config from a browser as it will display `text/plain` and try to download `application/octet-stream`.

**Comment by edolstra** [comment]
@fzakaria Yeah, `text/x-<whatever>` sounds good to me.

**Comment by zimbatm** [comment]
technically speaking, the format happens to be compatible with `application/x-yaml`
