### ISSUE TITLE
nix-channel --update does not match nixos status page releases

### ISSUE THREAD

**Issue by barryfm** [NixOS/nixos-org-configurations#169]
The build fetched with 'nix-channel --update' is behind the one shown on:
https://status.nixos.org/

For example currently the nix status page shows for nixos-21.05 the hash 1e5c35dfbc8
However https://nixos.org/channels/nixos-21.05 redirects to:
https://releases.nixos.org/nixos/21.05/nixos-21.05.2873.6bfe71f2a4e

**Comment by ilkecan** [comment]
Well now, ~4 hours later from your message `curl -LIs -o /dev/null -w %{url_effective} "https://nixos.org/channels/nixos-21.05"` outputs "https://releases.nixos.org/nixos/21.05/nixos-21.05.2981.1e5c35dfbc8". Similar thing happened to me for your first message on Discourse but that was also ~10 hours later after your message, so I didn't say anything.

**Comment by zimbatm** [comment]
It's a Fastly caching issue.
```
$ curl -I https://channels.nixos.org/nixos-21.05/git-revision
HTTP/2 301 
location: https://releases.nixos.org/nixos/21.05/nixos-21.05.2981.1e5c35dfbc8/git-revision
server: AmazonS3
via: 1.1 varnish, 1.1 varnish
access-control-allow-origin: *
accept-ranges: bytes
date: Tue, 07 Sep 2021 09:31:23 GMT
age: 6762
x-served-by: cache-bwi5163-BWI, cache-cdg20760-CDG
x-cache: HIT, HIT
x-cache-hits: 1, 1
x-timer: S1631007084.993718,VS0,VE1
content-length: 0

$ curl -I https://nix-channels.s3.amazonaws.com/nixos-21.05/git-revision
HTTP/1.1 200 OK
x-amz-id-2: 7uebzF465llcnqZI3qUg/ZLAuOHIzg/RDHohZvlXNk23VV9oYt2Wn/vW/WigdPUKHaGEUGn5o0k=
x-amz-request-id: DEK0GR46XTMSK31Z
Date: Tue, 07 Sep 2021 09:31:36 GMT
Last-Modified: Mon, 06 Sep 2021 22:15:33 GMT
ETag: "d41d8cd98f00b204e9800998ecf8427e"
x-amz-website-redirect-location: https://releases.nixos.org/nixos/21.05/nixos-21.05.2987.fd6dba47199/git-revision
Accept-Ranges: bytes
Content-Type: binary/octet-stream
Server: AmazonS3
Content-Length: 0

```

**Comment by zimbatm** [comment]
The default Fastly TTL is 86400s => 24h.

**Comment by zimbatm** [comment]
The TTL is 5 minutes now

**Comment by barryfm** [comment]
Currently I see the nixos-21.05 latest git hash at 276671abd10 while the URL points to 12eb1d16ae3.

This has been this way since at least last night. 

Maybe `nix-channel --update` should really select the releases from query to the prometheus api
rather than indirectly though a web page link address.

**Comment by vcunat** [comment]
`12eb1d16ae3` was reportedly pushed before the this issue was closed, so I suspect that one still had longer TTL.

**Comment by vcunat** [comment]
From my end I see a fresh one now.  (I didn't when I last commented)

**Comment by barryfm** [comment]
Actually there seems to be 3 times involved:

 1) When the channel link is updated.  Seen via:
    https://api.github.com/repo/NixOS/nixpkgs/branches/nixos-21.05
    which is rate lmited by github so can't be use directly.
 2) When https://status.nixos.org/ sees the change, which I assume can be fetched with:
    https://status.nixos.org/prometheus/api/v1/query?query=channel_update_time
  3) When the nix-channel program sees the update which is from the redirect address at:
    https://nixos/org/channels/nixos-21.05 changes.

It would be nice if what nix-channel saw matched what showed up on status.nixos.org,
so when one saw an update, and then tried to update their system, they would actually
get updated rather than ending up confused.

**Comment by colemickens** [comment]
This came up because folks in IRC were noticing that `nix-channel --update` is giving them **days stale release**.

**Comment by vcunat** [comment]
Yes, I still see bad caching for `https://channels.nixos.org/nixos-unstable/` (and inside).  The git revision updated earlier than 9:09 GMT (`2cf9db0e3d4..9aeeb7574fb`), and the URL still won't reflect that change 11 hours later.
<details><pre>
* Using Stream ID: 1 (easy handle 0x1b8d9a0)
> GET /nixos-unstable/git-revision HTTP/2
> Host: channels.nixos.org
> user-agent: curl/7.76.1
> accept: */*
> 
< HTTP/2 301 
< location: https://releases.nixos.org/nixos/unstable/nixos-21.11pre323079.2cf9db0e3d4/git-revision
< server: AmazonS3
< via: 1.1 varnish, 1.1 varnish
< access-control-allow-origin: *
< accept-ranges: bytes
< date: Sun, 17 Oct 2021 20:24:39 GMT
< age: 18
< x-served-by: cache-bwi5135-BWI, cache-vie6342-VIE
< x-cache: HIT, HIT
< x-cache-hits: 1, 1
< x-timer: S1634502280.687875,VS0,VE1
< content-length: 0
<
</pre></details>

**Comment by wamserma** [comment]
Can we show sth. like "populating cache" in the status column on https://status.nixos.org/ while Hydra loads the build results into S3 or have some other status reporting from https://github.com/NixOS/nixos-channel-scripts/blob/master/mirror-nixos-branch.pl? Log runtime of this script to Prometheus?
Once this process is done it might help to actively purge the cache on Fastly.

**Comment by wamserma** [comment]
Issue is creeping up again. channel.nixos.org is stuck at nixos-21.11.334247.573095944e7 while https://hydra.nixos.org/job/nixos/release-21.11/tested#tabs-status reports nixos-21.11.334461.982457a29a0 finished successfully 12 hours ago.
https://monitoring.nixos.org/grafana/ says '502 Bad Gateway'.

**Comment by vcunat** [comment]
Well, these are different issues than discussed originally in this thread.

This case of stuck channel is just several hours for now, probably best discussed on chat, https://matrix.to/#/#infra-alerts:nixos.org or https://matrix.to/#/#infra:nixos.org I think.

Grafana was take down intentionally due to a CVE... maybe its update waits exactly on this 21.11 channel bump (or maybe it was in some of the previous ones).  It was discussed in there, too.

**Comment by vcunat** [comment]
BTW, I _think_ these delays are lately mainly because of https://github.com/NixOS/nixos-channel-scripts/issues/53 (but I'm not sure... don't even have access to read logs from there)

**Comment by wamserma** [comment]
> Grafana was take down intentionally due to a CVE... maybe its update waits exactly on this 21.11 channel bump (or maybe it was in some of the previous ones). It was discussed in there, too.

So it should display a 503 or maybe even a static page with more info.

**Comment by vcunat** [comment]
No point spending time on that IMHO, rather bring it back up.  These things are among systems where only a very small handful people have access, and they really work on it in their free time...
