### ISSUE TITLE
Scale up/down Hydra resources during Release season

### ISSUE THREAD

**Issue by tomberek** [NixOS/nixos-org-configurations#186]
**Is your feature request related to a problem? Please describe.**

Potential limitation in build resources slowing down staging-next builds.

**Describe the solution you'd like**

Scale up x86_64-linux and aarch64-linux build machines for ZHF/release purposes.
Scale back down after release.

This is a way to target our resource spending towards more critical time. 

**Describe alternatives you've considered**

- Create an independent and dedicated Hydra on staging-next, ZHF/release

**Additional context**

21.11 Release
@jonringer @nrdxp

**Comment by grahamc** [comment]
:+1: we've scaled up by a handful of machines for ZHF, so I'm going to close this -- if we need more, please re-open or make a new ticket!

**Comment by tomberek** [comment]
@grahamc we can scale down
