### ISSUE TITLE
Establish a Cloudflare Pages account at the Foundation level

### ISSUE THREAD

**Issue by lucperkins** [NixOS/nixos-org-configurations#224]
At the moment, [nix.dev](https://github.com/nixos/nix.dev) uses [Domen](https://github.com/domenkozar)'s personal [CloudFlare Pages](https://pages.cloudflare.com/) account for publishing the site. As nix.dev is currently a semi-official&mdash;and intended to eventually be fully official&mdash;information outlet for Nix, it would be best to have an account managed by the Foundation instead.

The practical issue that brought this up is that nix.dev doesn't currently have per-pull-request deploy previews, which is a feature provided by CloudFlare Pages. Some members of the Nix docs team (including myself) would like to see that enabled and would currently need to go through Domen for that. Nothing against the lovely Domen, of course, but a Foundation-level account would enable us to distribute admin capabilities across select members of the Foundation/docs team.

In terms of cost, the free plan would likely suffice to begin with. In the event that a higher plan is needed, multiple projects could likely be covered by a pro plan simultaneously.

![image](https://user-images.githubusercontent.com/1523104/198106210-88cb4845-25af-421d-8018-55a1a81a84ce.png)

**Note**: this is a duplicate of https://github.com/NixOS/nixos-foundation/issues/18 and filed here on the advice of @zimbatm.

**Comment by zimbatm** [comment]
> Nameserver change launched. Please allow 12-24 hours for propagation before testing.

I imported the A and AAAA records and updated the NS records on Gandi.

**Comment by zimbatm** [comment]
Done!

**Comment by delroth** [comment]
I know I'm kind of late on this, but we already use Netlify for some similar use cases. Should we aim to consolidate those? As far as I understand, they very much do the same thing.

**Comment by delroth** [comment]
(Specifically, re: pull request previews, https://docs.netlify.com/site-deploys/deploy-previews/)

**Comment by zimbatm** [comment]
Yes, probably. The main reason we have both is that nix.dev was independently built on Cloudflare Pages. A historical accident.
