### ISSUE TITLE
Running first-time-contribution-tagger on offical infra

### ISSUE THREAD

**Issue by Janik-Haag** [NixOS/nixos-org-configurations#258]
**Is your feature request related to a problem? Please describe.**
having every first-time contribution label tagged by my user is definitively not ideal and people asking me if we can run this on offical infra.

**Describe the solution you'd like**

Hosting github.com/janik-Haag/first-time-contribution-tagger on official infra

**Describe alternatives you've considered**
Self-Hosting and nix-community infra.

**Additional context**
See https://discourse.nixos.org/t/showing-first-time-contributors-some-love/29105
And https://github.com/nix-community/infra/issues/634#issuecomment-1594698073

**Comment by Janik-Haag** [comment]
pinging @JulienMalka since they merged the last pr in this repo :see_no_evil:

**Comment by JulienMalka** [comment]
This looks like a proper usage of the new non-critical infra to me ! 
Could you please open a pull request with the necessary changes to the `non-critical-infra` folder so that we can review and deploy the changes ?

**Comment by Janik-Haag** [comment]
Sure, I'll open a draft pr once I find time, I obviously can't test it and the bot needs a github api token to add labels which has to be added with some kind of secret-management.

**Comment by JulienMalka** [comment]
About the API token, I don't really know how we should handle that. You could maybe create an account for that where it is clear that this is a bot belonging to the general Nix community. What do you think @zimbatm ?

**Comment by zimbatm** [comment]
@JulienMalka you can open a new bot account, and add it to Bitwarden. You can use sysadmin + botname _AT_ nixos as the email address.

@Janik-Haag would you be open to moving the repo to this organization?

**Comment by Janik-Haag** [comment]
> would you be open to moving the repo to this organization?

Sure :D

**Comment by JulienMalka** [comment]
Thank you @Janik-Haag for bringing a first time contribution tagger to the community! This has been deployed :)

**Comment by zimbatm** [comment]
Do we have any examples of this tool doing its thing? :)

**Comment by JulienMalka** [comment]
Yes, search in nixpkgs PRs and filter with tag "first contribution" :)

**Comment by Janik-Haag** [comment]
@NixOSInfra should probably have a link to this repo in it's deception for issues or have it's own repo to collect issues.
