### ISSUE TITLE
New box for the new infra team

### ISSUE THREAD

**Issue by zimbatm** [NixOS/nixos-org-configurations#260]
We have access to this Hetzner box to do whatever we want with it: root@65.109.26.213

It's currently booted in rescue mode, with your SSH keys added to it.

I would suggest creating a new folder for that machine in the repo, and to bootstrap it with nixos-anywhere, or manually. And then we can start moving some of the services from the delft folder there?

**Comment by Mic92** [comment]
In case you go with nixos-anywhere feel free to ask questions here: https://matrix.to/#/#nixos-anywhere:nixos.org
We have a lot of experience with hetzner in particular and also support terraform out-of-the box: https://github.com/numtide/nixos-anywhere/tree/main/terraform

**Comment by JulienMalka** [comment]
I am going to bootstrap the machine during this week-end.

**Comment by JulienMalka** [comment]
Done, sorry for the delay :)
