### ISSUE TITLE
Ipv6 support for https://nixos.org

### ISSUE THREAD

**Issue by Mic92** [NixOS/nixos-org-configurations#29]
## Issue description

According to this document https://aws.amazon.com/blogs/aws/aws-ipv6-update-global-support-spanning-15-regions-multiple-aws-services/ there is ipv6 support for eu-west-1, where the website is apparently hosted. When we also have ipv6 support for the homepage, ipv6 support is complete.

### Steps to reproduce

```
$ dig AAAA nixos.org

; <<>> DiG 9.10.4-P6 <<>> AAAA nixos.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27168
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;nixos.org.                     IN      AAAA

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Apr 25 10:03:41 CEST 2017
;; MSG SIZE  rcvd: 38
```

#### Things to solve this issue:

- [ ] Add ipv6 support for AWS in [nixops](https://github.com/NixOS/nixops/)
- [ ] Allocate an ipv6 subnet in [nixos-homepage](https://github.com/NixOS/nixos-homepage//)

**Comment by Mic92** [comment]
Does nixops support ipv6 allocations? If yes, I could give it a try.

**Comment by MrSorcus** [comment]
Up. Can't install/upgrade NixOS without IPv4. It's so sad.

**Comment by Mic92** [comment]
Nixops cannot handle ipv6 completely, some remaining parts have to upgraded to boto3 for that.

**Comment by Mic92** [comment]
https://github.com/NixOS/nixops/search?utf8=%E2%9C%93&q=boto&type=

**Comment by vcunat** [comment]
> Up. Can't install/upgrade NixOS without IPv4. It's so sad.

cache.nixos.org has IPv6, and I think it's been so for a long time.

**Comment by lschuermann** [comment]
I'm not a big fan of Cloudflare in general, but I think they are offering a [hotfix](https://blog.cloudflare.com/introducing-cloudflares-automatic-ipv6-gatewa/) that might work in this situation. I don't know how their DDoS protection and captcha nonsense will behave with all the Nix clients however.

Regardless, IPv6 on the main website shouldn't be something that needs to be discussed in 2018. This is completely breaking my v6-only setup and makes me pretty sad. :(
As https://nixos.org/channels only serves redirects to the cloudfront.net sites and therefore shouldn't cause too much load, I've now setup a proxy on a small shared hoster, effectively MITM'ing myself. Seems to be the most elegant solution in the meantime.

**Comment by vcunat** [comment]
Tangential thought: for v6-only machines I would expect it's usually practical to have some more general fallback solution anyway, e.g. NAT64 + DNS64.

**Comment by bchallenor** [comment]
I would like to see this too. I have some hosts that I am trying to make IPv6-only, but cannot because of nixos.org/channels.

**Comment by rkeene** [comment]
This is holding back my use of Nix on my IPv6-only hosts (which vastly outnumber my IPv4-capable hosts at this point) as well.

**Comment by Mic92** [comment]
Please use the reaction actions in github instead of posting `me too` posts.

**Comment by bennofs** [comment]
This is not only important for `nixos.org/channels` but also for `nixos.org/releases` which makes it hard to setup a nix remote builder on ipv6-only hosts (which are often cheaper).

**Comment by vcunat** [comment]
On a brief look I'd expect this is all solved now.  I see AAAA for nixos.org, channels.nixos.org and releases.nixos.org (all CloudFront).

**Comment by davidak** [comment]
IPv6 work for https://nixos.org but this check shows that the DNS server don't support it.

![Screenshot from 2020-09-16 23-04-48](https://user-images.githubusercontent.com/91113/93392520-399ffa80-f871-11ea-846f-d74773054882.png)

https://ipv6-test.com/validate.php

**Comment by vcunat** [comment]
Oh, right.  In the worst case, people can work around that e.g. by utilizing some public resolver, but it's not ideal.

**Comment by zimbatm** [comment]
It's because we are still using the domain registrar DNS. These could be switched to using Netflify as a DNS provider.

**Comment by vcunat** [comment]
The current provider is NS1 (looking at the DNS records), and they say they plan to add IPv6 everywhere (regardless of our case).  Still, I suspect you planned to switch DNS for other reasons anyway.

**Comment by zimbatm** [comment]
Eelco is the only one who has access to the name registrar.

**Comment by Mic92** [comment]
Alternatively one could also cloudflare (they also support to be used for DNS hosting without the proxy stuff) or Hetzner (https://www.hetzner.de/dns-console) with no extra cost.

**Comment by vcunat** [comment]
> IPv6 work for https://nixos.org but this check shows that the DNS server don't support it.

This shows green now 📈   No other problem remains, I expect?

**Comment by davidak** [comment]
I see no issues. We can close it.

When anyone has any issues, they can open a new one.

**Comment by davidak** [comment]
I see no issues. We can close it.

When anyone has any issues, they can open a new one.

**Comment by mbana** [comment]
@zimbatm, please re-open the issue ... 

Can anyone on a IPv6 only machine please try the below:

```sh
$ sh <(curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install) --daemon
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to nixos.org port 443 after 4 ms: Couldn't connect to server
$ ping -c1 google.com
PING google.com (2a00:1450:4007:810::200e) 56 data bytes
64 bytes from pnpara-ag-in-x0e.1e100.net (2a00:1450:4007:810::200e): icmp_seq=1 ttl=117 time=1.20 ms

--- google.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 1.202/1.202/1.202/0.000 ms
$ ping -c1 bing.com
PING bing.com (2620:1ec:33:1::10) 56 data bytes
64 bytes from 2620:1ec:33:1::10: icmp_seq=1 ttl=49 time=1.68 ms

--- bing.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 1.684/1.684/1.684/0.000 ms
$ ping -c1 github.com
ping: connect: Network is unreachable
$
```

Thanks,
\- Bana
