### ISSUE TITLE
tarballs.nixos.org stuck at 21.05

### ISSUE THREAD

**Issue by Artturin** [NixOS/nixos-org-configurations#291]
https://github.com/NixOS/nixos-org-configurations/blob/fcd8d311946f42630f9720ee2d347deb6bdb091e/modules/tarball-mirror.nix#L14

https://github.com/NixOS/nixos-org-configurations/pull/242 and fixing the credentials would fix this

In https://discourse.nixos.org/t/is-tarballs-nixos-org-stuck-at-19-09/13647/6 @vcunat said
>  Now there’s some issue around AWS credentials

in the matrix room @vcunat said that there was the following error

> evaluation returned 26998 tarballs
Net::Amazon::S3: Amazon responded with 403 Forbidden

Note that those were in march so there may no longer be errors but the pr should be merged

**Comment by mweinelt** [comment]
Fixed in https://github.com/NixOS/nixos-org-configurations/commit/b87e0b1e295468101f0d36210ad0efe33756d776 and https://github.com/NixOS/nixos-org-configurations/commit/00e75df10e65e90382abe7d07a1871c8ec50ebb5.

**Comment by vcunat** [comment]
No idea how the S3 part got fixed, but it really does seem to work now.
```
$ git checkout a77ab169  # 23.11 that was last used to pull tarballs
$ nix build -f. knot-dns.src -L --rebuild  # some recently new tarball
knot> trying https://tarballs.nixos.org/sha256/aab40aab2acd735c500f296bacaa5c84ff0488221a4068ce9946e973beacc5ae
knot>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
knot>                                  Dload  Upload   Total   Spent    Left  Speed
knot>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
knot> 100 1549k  100 1549k    0     0  8497k      0 --:--:-- --:--:-- --:--:-- 8497k
```
