### ISSUE TITLE
nix.dev: Cloudflare not deploying 

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nixos-org-configurations#300]
**Affected service**

nix.dev website

**Describe the issue**

Related: https://github.com/NixOS/nix.dev/issues/772

Unbeknownst to the @NixOS/documentation-team, Cloudflare _requires_ Poetry because it can't Nix, so when we removed it that broke deployments.

![](https://matrix-client.matrix.org/_matrix/media/v3/download/numtide.com/TYimcxxnxEcYULTKbfvaPLCJ)

**Proposal**

Please help us with:
- Add a Hydra jobset with a nix.dev output tarball, so we can unpack the result anywhere
- Optionally move to Fastly, since other infrastructure is hosted there

There's no good reason for us to revert to Poetry because that requires beginners to understand more things about the setup, so that should be the last resort.

**Comment by delroth** [comment]
> Optionally move to Fastly, since other infrastructure is hosted there

s/Fastly/Netlify/ I imagine?

**Comment by delroth** [comment]
Taking the discussion to https://github.com/NixOS/nix.dev/issues/772 - keeping this open on the infra side to track making sure nix.dev is properly onboarded onto NixOS's infra and they are not blocked on us.

**Comment by fricklerhandwerk** [comment]
This is resolved. Thanks a lot @delroth for your quick help.

If you'll ever advertise what you're doing in some sort of retrospective, that would be a success story.
