### ISSUE TITLE
Remove and destroy fastly_tls_subscription.cache-staging

### ISSUE THREAD

**Issue by delroth** [NixOS/nixos-org-configurations#302]
b3385ad3768154778afafe042b74dd34eb1ecbba has cleaned up ~all of cache-staging, but the TLS subscription remains because I can't destroy it myself. Can someone with more Fastly access take care of cleaning it up?

Assigning to @zimbatm by default since I don't know precisely who has that access.

**Comment by zimbatm** [comment]
It's just eelco and me that have access right now.
