### ISSUE TITLE
nix.dev: enable branch protection on master

### ISSUE THREAD

**Issue by proofconstruction** [NixOS/nixos-org-configurations#303]
**Is your feature request related to a problem? Please describe.**

Currently, anyone added to the Documentation Team can push to `master` at will. Recently, there was an incident where a contributor pushed an incorrectly-signed commit to the wrong git remote (the _upstream_ `master`, when they should have pushed to their fork), requiring manual remediation.

**Describe the solution you'd like**

[Branch protection rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches) should be enabled for nix.dev to prevent erroneous pushes.

**Comment by cole-h** [comment]
I've enabled the setting that requires PRs before merging into `master`:

<img width="787" alt="image" src="https://github.com/NixOS/nixos-org-configurations/assets/28582702/c54a9b22-1aec-47f8-b134-9fc50be78db3">

Let me know of any other specific settings you'd like to see enabled. (I'll leave this open until someone chimes in if this is enough protection, or if you want more.)

**Comment by cole-h** [comment]
However, it looks like the documentation team only has "Maintain" permissions on the nix.dev repo (see image below), which as far as I understand doesn't imply "Write" permissions (https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization), so maybe there's another issue...?

<img width="771" alt="image" src="https://github.com/NixOS/nixos-org-configurations/assets/28582702/27ecadf7-5ea3-4dee-84ab-d9f92e1022eb">

**Comment by proofconstruction** [comment]
Maintain does indeed imply Write, per the link you posted:
![image](https://github.com/NixOS/nixos-org-configurations/assets/74747193/daf8e300-15a0-42b5-ad29-ab5f73374905)

**Comment by cole-h** [comment]
Ah, cool, I can't read. Cheers.

**Comment by fricklerhandwerk** [comment]
It would be good if I got admin permissions, then we wouldn't have to bother the infra team for such trivialities.

**Comment by delroth** [comment]
(Jeez, the GH UI is so confusing for assignees... sorry.)

Sending to @zimbatm to handle https://github.com/NixOS/nixos-org-configurations/issues/303#issuecomment-1801216393 and/or close this issue.

**Comment by zimbatm** [comment]
We need a declarative tool to manage users and repo configuration. I don't like the idea of people randomly clicking around the consuming GH UI. But in the meantime, I gave fricklhandler permission.
