### ISSUE TITLE
Migrate ngi0 infra to dedicated repository

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixos-org-configurations#326]
Hi @Ericson2314, @cleeyv, @lorenzleutgeb, @tomberek, @thufschmitt!

We talked today about the state of the infra with all infra members, and we agreed that it would be good to move ngi0 infra out of nixos-org-configurations. The reasons are that this would ultimately benefit you by unblocking your work on this infrastructure, as well as stop consuming our review bandwidth.

It would ultimately result in a better workflow for you guys, so what do you think?

The new home could be over at https://github.com/ngi-nix, if that is related, but we can also create a repo on the NixOS org.

WDYT?

**Comment by lorenzleutgeb** [comment]
I was never bit by limited review bandwidth, and otherwise did not interact with the infra team much, so I am quite neutral, and trust your judgement that it would be better to move. However, are there any downsides of moving that we should be aware of?

I think that github.com/ngi-nix is related, and that it would be a good namespace. Mentioning owners of that org, for their comment: @fricklerhandwerk @mightyiam

**Comment by mweinelt** [comment]
> However, are there any downsides of moving that we should be aware of?

None, that I am aware of.

**Comment by Ericson2314** [comment]
I have no objections.

**Comment by fricklerhandwerk** [comment]
Sounds fine to me. Would be reasonable to move that into `ngipkgs` once migrated, so it can live together with the code right there.

**Comment by mightyiam** [comment]
Are we talking about moving it to a different runner computer?

**Comment by mightyiam** [comment]
I wouldn't like my lack of context and possible catching up to delay whatever decision and follow up action. Just trying to learn.

**Comment by zimbatm** [comment]
Ok, I created https://github.com/NixOS/ngi-infra as a placeholder to put the code in. We can decide where to move the repo later.

In this model, the underlying computer would stay the same, and the infra team would still hold access to that hardware and DNS records. At the same time, the NGI team can independently deploy configuration changes to their Hydra instance.

**Comment by zimbatm** [comment]
Invited @fricklerhandwerk and @mightyiam to the https://github.com/orgs/NixOS/teams/ngi team. You should have permission to add missing team members.

**Comment by fricklerhandwerk** [comment]
NGI0 infra config now lives in https://github.com/ngi-nix/ngi0-infra
