### ISSUE TITLE
Clean up domain list

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixos-org-configurations#34]
Here is a rough sorting of domains to drop / keep, based on what just redirected back to nixos.org, domains I'd never heard of before, or were showing a "website maintenance" page, plus a couple I have heard of but nobody uses:

Drop:
ts.nixos.org
svn.nixos.org
status.nixos.org * never updated since I came around ...
stan.nixos.org
releases.nixos.org * I wonder how much traffic this gets
mturk.nixos.org
monitor.nixos.org
lucifer.nixos.org
losser.nixos.org
barbrady.nixos.org

Keep:
cache.nixos.org
hydra.nixos.org
weekly.nixos.org
conf.nixos.org
tarballs.nixos.org
planet.nixos.org

Domain list from https://github.com/NixOS/nixos-org-configurations/pull/33#issuecomment-323042489

**Comment by grahamc** [comment]
domain|ready for preload|serves https|redirects to https|serves STS|comments
-|-|-|-|-|-
cache.nixos.org| ✔️ |✔️ | ❌ | ❌ |it'd be ideal to have it also redirect HTTP to HTTPS. I'm not sure this is possible. From what I'm reading, CF can't send STS headers
hydra.nixos.org|✔️ |✔️ |✔️ |✔️ |
weekly.nixos.org|❌ |❌ |❌ |❌ |hosted on github pages, no support for SSL. Move to nixos.org box?
conf.nixos.org |❌ |❌ |❌ |❌ |hosted on github pages, no support for SSL Move to nixos.org box?
tarballs.nixos.org|❌ |❌ |❌ |❌ |hosted on CloudFront. Enable ACM & TLS?`
planet.nixos.org|❌ |❌ |❌ |❌ |hosted on the nixos.org box. enable LetsEncrypt?

**Comment by zimbatm** [comment]
GitHub added support for HTTPS so both conf and weekly are now available over HTTPS

**Comment by zimbatm** [comment]
I'm pretty sure all of that has been cleaned during the Netlify DNS migration.
