### ISSUE TITLE
Monitoring / logs for website build

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-org-configurations#52]
It would be easier to figure out and fix issues like [nixos-homepage#232](https://github.com/NixOS/nixos-homepage/pull/232) and #41 with log access.

Monitoring the website build, even for simple "hey, look, I failed", would at least let us act more quickly into figuring out a solution. A month is kinda slow :/.

(I have no actual knowledge or propositions for this.)

**Comment by davidak** [comment]
@samueldr is this still needed?

**Comment by samueldr** [comment]
Indeed it's not an issue anymore.
