### ISSUE TITLE
Users are reporting some issues with cache.nixos.org - gather information here

### ISSUE THREAD

**Issue by rbvermaa** [NixOS/nixos-org-configurations#57]
Issue to centralize some of the issues some users are having with cache.nixos.org after the Fastly.com switch.

**Comment by matthewbauer** [comment]
I'm getting it every time I try to use nix-index:

```
$ nix-index
+ querying available packages

error: fetching the references of store path '/nix/store/f03qiw1qz47qx685f2wfb76crxsp0ymg-node-grunt-cli-1.3.1' failed
caused by: request GET 'http://cache.nixos.org/f03qiw1qz47qx685f2wfb76crxsp0ymg.narinfo' failed with HTTP error 403 Forbidden
```

It looks like it's a different url failed each time.

**Comment by rbvermaa** [comment]
@matthewbauer The 403 is expected, as that is what S3 returns when an object does not exist. However, it is weird that nix would fail on that. @edolstra any idea how that could happen?

**Comment by rbvermaa** [comment]
It might be that the error doesn't come from nix, but from nix-index, as well.

**Comment by rbvermaa** [comment]
Looked at the nix-index code, and indeed error seems to come from nix-index, specifically https://github.com/bennofs/nix-index/blob/master/src/hydra.rs#L173 . 

This is probably triggered by cache.nixos.org returning the 403 error that S3 returns on objects that do not exist. The Cloudfront setup returned a 404. Will see if we can change this to a 404.

**Comment by rbvermaa** [comment]
@matthewbauer We have changed cache.nixos.org to return a 404. There might be some URL's that still have the 403 cached, but these should disappear in the next few hours, and return the 404. This should make nix-index work again.

**Comment by rbvermaa** [comment]
@NinjaTrappeur Thanks for the info. Does a curl call work without issues? e.g. could you post output of:

```curl -v https://cache.nixos.org/hig48ji0b68r4d47gd83jpnmpi3hrfxi.narinfo```

**Comment by rbvermaa** [comment]
Also, are you using IPv6? Just found similar issue here: https://community.fastly.com/t/i-often-cant-access-fastly-servers-using-https-ipv6-rst-packets-received/1317/4 . Perhaps it is related.

**Comment by NinjaTrappeur** [comment]
```
~ » curl -v https://cache.nixos.org/hig48ji0b68r4d47gd83jpnmpi3hrfxi.narinfo              ninjatrappeur@thinkpad-nix
*   Trying 2a04:4e42:1d::729...
* TCP_NODELAY set
* Connected to cache.nixos.org (2a04:4e42:1d::729) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to cache.nixos.org:443 
* stopped the pause stream!
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to cache.nixos.org:443 
------------------------------------------------------------
~ » curl -v -4 https://cache.nixos.org/hig48ji0b68r4d47gd83jpnmpi3hrfxi.narinfo           ninjatrappeur@thinkpad-nix
*   Trying 151.101.38.217...
* TCP_NODELAY set
* Connected to cache.nixos.org (151.101.38.217) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Fastly, Inc.; CN=v2.shared.global.fastly.net
*  start date: Oct 15 11:17:24 2018 GMT
*  expire date: Mar 20 20:22:20 2019 GMT
*  subjectAltName: host "cache.nixos.org" matched cert's "cache.nixos.org"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign CloudSSL CA - SHA256 - G3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x13bc2b0)
> GET /hig48ji0b68r4d47gd83jpnmpi3hrfxi.narinfo HTTP/2
> Host: cache.nixos.org
> User-Agent: curl/7.61.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 404 
< server: Varnish
< retry-after: 0
< content-type: text/html
< accept-ranges: bytes
< accept-ranges: bytes
< date: Tue, 16 Oct 2018 10:11:44 GMT
< via: 1.1 varnish
< x-served-by: cache-ams4431-AMS
< x-cache: MISS
< x-cache-hits: 0
< x-timer: S1539684705.547020,VS0,VE88
< content-length: 3
< 
* Connection #0 to host cache.nixos.org left intact
404%                                               
```

Looks like an IPv6 error.

**Comment by NinjaTrappeur** [comment]
Yup, looks related, I have the same router.

I'm gonna look for an option to force IPv4 on nix calls.

Thanks you for your help!

**Comment by bflyblue** [comment]
I'm also hitting the MAX_CONCURRENT_STREAMS thing on IPv4

```
curl -v https://cache.nixos.org/131qzkaw7fb357c1f1a5145wjbzi6f7c.narinfo
*   Trying 151.101.2.217...
* TCP_NODELAY set
* Connected to cache.nixos.org (151.101.2.217) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Fastly, Inc.; CN=v2.shared.global.fastly.net
*  start date: Oct 17 19:11:27 2018 GMT
*  expire date: Mar 20 20:22:20 2019 GMT
*  subjectAltName: host "cache.nixos.org" matched cert's "cache.nixos.org"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign CloudSSL CA - SHA256 - G3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x1af92a0)
> GET /131qzkaw7fb357c1f1a5145wjbzi6f7c.narinfo HTTP/2
> Host: cache.nixos.org
> User-Agent: curl/7.61.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 404
< server: Varnish
< retry-after: 0
< content-type: text/html
< accept-ranges: bytes
< accept-ranges: bytes
< date: Thu, 18 Oct 2018 09:28:12 GMT
< via: 1.1 varnish
< x-served-by: cache-jnb7524-JNB
< x-cache: MISS
< x-cache-hits: 0
< x-timer: S1539854892.632701,VS0,VE1179
< content-length: 3
<
```

**Comment by rbvermaa** [comment]
@hamishmack Sorry, I missed the notification for this issue. I have contacted Fastly support, to see if they can help diagnose this issue, will update here when I hear back.

**Comment by rbvermaa** [comment]
We've changed some settings to be able to debug this issue better, based on suggestions by Fastly. Hopefully this gives us some more information about the 503 errors.

If you experience this again on your machine, can you let us know and go to https://www.fastly-debug.com/ and post the information here?

**Comment by terlar** [comment]
I experience this issue and just disabled IPv6 to be able to upgrade my NixOS, going to that page it just infinitely spinns saying`Collecting data please wait...`, I waited for 30 minutes, wasn't sure if it was supposed to return something by then.

**Comment by rbvermaa** [comment]
@terlar Does the page spin after you switched to IPv4, or when you were still on IPv6?

**Comment by terlar** [comment]
Both as far as I can remember. I am currently on vacation, but I will double check when I have access to my computer.

**Comment by samueldr** [comment]
IRC report:

  * https://logs.nix.samueldr.com/nixos/2019-02-20#1550675671-1550675476;

**Comment by millettjon** [comment]
I started getting lots of these a few hours ago:
warning: unable to download 'https://cache.nixos.org/ax3igj2aglvv46vkcpmyklr6lcqlwz7z.narinfo': Couldn't connect to server (7); retrying in 253 ms
warning: unable to download 'https://cache.nixos.org/im74kvbg0swj3akq4gcbwnlw8pj6lz1a.narinfo': Couldn't connect to server (7); retrying in 267 ms
w
Using wget returns 404 for the same urls.


Here is the fastly report. Note that is doesn't seem to complete. I waited more than 5 minutes and it is still working. The partial information is below.
| Debug
Collecting data please wait.

Client IP Info
IP	181.226.182.157
AS Name	
AS Number	
City	
Continent	
Country	
State	
Resolver IP Info
IP	
AS Name	
AS Number	
Country Code	
Server Connection Info
IP	151.101.0.64
Datacenter	SCL
BW to server	
Congestion Window	
Next Hop	
RTT	
Delta Retransmits	
Total Retransmits	
Request Info
Time	Wed Feb 20 2019 15:42:24 GMT-0500 (EST)
Host	www.fastly-debug.com
Accept	text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
User-Agent	Mozilla/5.0 (X11; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0
Accept-Language	en-US,en;q=0.5
Accept-Encoding	gzip
X-Forwarded-For	181.226.182.157

**Comment by millettjon** [comment]
Still having this issue. Curl now works with ipv4 (-4) option but not with (-6). Any way to force nix to use ipv4?

**Comment by terlar** [comment]
You can disable ipv6. I am currently using `networking.enableIPv6 = false;` to avoid this issue.

**Comment by grahamc** [comment]
I've been chatting with Fastly support. They've told me a lot of the 503 errors are due to a [low connect timeout between Fastly and S3](https://docs.fastly.com/guides/debugging/changing-connection-timeouts-to-your-origin). I've changed this value from 1000ms to 2000ms. We'll start with this change and see how the number of reports over time changes.

**Comment by grahamc** [comment]
I'm going to close this issue. I know not every error is addressed here, but also it is impossible to address every issue permanently. If you experience a similar issue, please open a ticket for the specific error you find, so we can triage and diagnose per-error. Please also link back to this one, so it can help route people to a more specific issue. Thank you for the help and reports, sorry it took a while to address it.

**Comment by grahamc** [comment]
Here are two graphs of 503s.

Before:
![Screenshot_2019-03-16 Fastly Stats (cache nixos org)(1)](https://user-images.githubusercontent.com/76716/54474949-c9b73c80-47c1-11e9-9010-4528cb837253.png)

After:
![Screenshot_2019-03-16 Fastly Stats (cache nixos org)](https://user-images.githubusercontent.com/76716/54474947-c2902e80-47c1-11e9-99cf-4cf17bf516fc.png)

I've gone ahead and increased the timeout connect from 2000ms to 5000ms.
