### ISSUE TITLE
Drop ike?

### ISSUE THREAD

**Issue by Ekleog** [NixOS/nixos-org-configurations#58]
Ike has been failing builds transiently a few times now, including in the middle of a webkit build that didn't use network access or anything, meaning that the issue appears to be RAM or disk-related.

And this doesn't sound good, because if the error occurs in eg. the final build-product, it may actually pass the compilation step and generate a broken binary.

In addition, these failing builds slow down the channel, as they need to be manually restarted for the channel to move forward.

I understand that ike is currently one of the most powerful machines in hydra, but maybe it'd make sense to try to disable it and see whether channel actually bump faster? (as there should be less transient failures)

**Comment by grahamc** [comment]
Closing for now. If it continues to act up, open a new issue?
