### ISSUE TITLE
Serve signed packages on the cache

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixos-org-configurations#8]
See https://github.com/NixOS/nix/issues/75#issuecomment-71452041, Hydra already signs packages, so the cache would need to copy the signatures and make signatures for already-made packages.

**Comment by copumpkin** [comment]
:+1:

**Comment by wmertens** [comment]
@edolstra @ikwildrpepper is there any way to help move this forward?

**Comment by wmertens** [comment]
@rbvermaa :-)

**Comment by rbvermaa** [comment]
Just patience, I believe @edolstra is busy with this.

**Comment by edolstra** [comment]
Done.

**Comment by wmertens** [comment]
Whee!
