### ISSUE TITLE
update AWS AMIs and Virtual Box Images to 19.09

### ISSUE THREAD

**Issue by disassembler** [NixOS/nixos-org-configurations#90]
A number of people asked me when we were updating the images to 19.09. Opening this issue to track it.

@edolstra @rbvermaa @AmineChikhaoui

**Comment by AmineChikhaoui** [comment]
I created a PR for the EC2 amis update https://github.com/NixOS/nixpkgs/pull/72186.

**Comment by AmineChikhaoui** [comment]
VirtualBox is also now up-to-date (in the plugin repo https://github.com/nix-community/nixops-vbox/commit/bff6054ce9e7f5f9aa830617577f1a511a461063)

**Comment by grahamc** [comment]
PR for EC2 is merged and backported.

**Comment by markuskowa** [comment]
I noticed that we do not have AMIs for eu-north-1 (EU, Stockholm). Would it be possible to add and an AMI for this region?
