### ISSUE TITLE
linked cache.nixos.org diagnostics script outdated

### ISSUE THREAD

**Issue by d-goldin** [NixOS/nixos-org-configurations#96]
Currently https://gist.github.com/grahamc/df1bb806eb3552650d03eef7036a72ba is linked as a diagnostics script for cache/CDN issues from https://cache.nixos.org/, but it's still geared towards cloudfront instead of Fastly.

I couldn't find any similar script provided by Fastly directly, so am not sure if there are any other particular domains or hosts that need checking aside from cache.nixos.org itself, thus am not proposing a concrete change here.

@thoughtpolice @grahamc

**Comment by thoughtpolice** [comment]
I'm working on something like this but the thing is, it's unclear *what* kind of diagnostics the previous script was really intending to provide, outside of just running extremely obvious checks like "is your router turned on". Which is fine, of course, sometimes the router's turned off!

We can do some better stuff, potentially, if we bake some extra logic into the CDN layer to give feedback. (For instance, an obvious one is "What Fastly datacenter is the user connecting to", which is potentially *extremely* relevant.) This has been part of my long-term goals with the new binary cache setup, but very low in priority vs having everything else work well.

I also think it would be nice if the script was actually `nix run`-able. For instance you could stuff a `default.nix` into the included gist that just used `<nixpkgs>` for dependencies (so you don't have to contact the cache anyway) to run everything for you.

Happy to hear any suggestions from Graham if he has them.

**Comment by zimbatm** [comment]
The index.html can now be changed with terraform over here: https://github.com/NixOS/nixos-org-configurations/blob/7d5ff0a5526edeedcf22a39f50fd72e12a137f65/terraform/cache/index.html#L47-L49 

All we need now is an updated diagnostic script.

**Comment by zimbatm** [comment]
I did a quick pass in 93f42d6a4a1aec223c223834aba640aa8a73cf49. Feel free to propose further improvements!
